// <auto-generated />
namespace KiDSisMvcWebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DropColumnBooksBooksCategori_Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropColumnBooksBooksCategori_Id));
        
        string IMigrationMetadata.Id
        {
            get { return "201805030432540_DropColumnBooksBooksCategori_Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
